# Generated by Django 5.2.5 on 2026-06-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_dailyrecommendation_remove_menuitem_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('image', models.ImageField(upload_to='restaurant_photos/')),
                ('is_visible', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
