# Generated by Django 5.2.5 on 2026-06-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_customerreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='reviews_background_image',
            field=models.ImageField(blank=True, upload_to='restaurant/'),
        ),
    ]
