# Generated by Django 5.2.5 on 2026-06-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_restaurantprofile_reviews_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='primary_contact_method',
            field=models.CharField(choices=[('phone', 'Phone'), ('email', 'Email')], default='phone', max_length=10),
        ),
    ]
