# Generated by Django 5.2.5 on 2026-06-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_restaurantprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='online_order_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='show_online_order',
            field=models.BooleanField(default=False),
        ),
    ]
