# Generated by Django 5.2.5 on 2026-06-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_restaurantprofile_online_order_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='online_order_image_left',
            field=models.ImageField(blank=True, upload_to='restaurant/'),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='online_order_image_right',
            field=models.ImageField(blank=True, upload_to='restaurant/'),
        ),
    ]
