# Generated by Django 5.2.5 on 2026-06-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_restaurantprofile_online_order_image_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='logo',
            field=models.ImageField(blank=True, upload_to='restaurant/'),
        ),
    ]
