# Generated by Django 5.2.5 on 2026-06-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_restaurantprofile_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='group_reservation_background_image',
            field=models.ImageField(blank=True, upload_to='restaurant/', verbose_name='group reservation background image'),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='group_reservation_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='group reservation manager email'),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='show_group_reservation',
            field=models.BooleanField(default=False, verbose_name='show group reservation section'),
        ),
    ]
