# Generated by Django 5.2.5 on 2026-06-07 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_restaurantprofile_group_reservation_background_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyrecommendation',
            options={'ordering': ['order', 'name']},
        ),
    ]
