# Generated by Django 5.2.5 on 2026-06-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_alter_dailyrecommendation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='happy_hour_items',
            field=models.TextField(blank=True, verbose_name='happy hour dishes'),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='happy_hour_schedule',
            field=models.TextField(blank=True, verbose_name='weekly happy hour time'),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='show_happy_hour',
            field=models.BooleanField(default=False, verbose_name='show happy hour section'),
        ),
    ]
